### ISSUE TITLE
Wordpress 4.9.1 Error on edit page

### ISSUE THREAD

**Issue by cihaneken** [zjhzxhz/Logger#1]
First I apologize for my English.
Some features will not work on the edit page and will cause errors.

The text editor key is not working.
The plugin buttons do not appear in the visual editor.
The display preferences key will not work.

These problems do not occur when experimenting with a different theme.
Logger Master shows these problems.

![](https://cardse.net/i/2017/12/11/d943a77a72747b785acf5e40be5e951e.png)
![ekran alintisi](https://user-images.githubusercontent.com/17432022/33846110-eb473458-dea5-11e7-8123-a3b96460db97.PNG)

**Comment by hzxie** [comment]
Sorry, I cannot reproduce your error.
Please check your configuration of your web server.

![screenshots](https://user-images.githubusercontent.com/1730504/33881332-6f61f1aa-df6f-11e7-9040-40c2d813bf50.png)

**Comment by hzxie** [comment]
You can also try to disable all plugins and see whether the problem exists.

**Comment by cihaneken** [comment]
I deleted the jquery.isotope.min.js file. the problem is resolved
