### ISSUE TITLE
Static files returns HTTP error 404

### ISSUE THREAD

**Issue by Linon419** [zjhzxhz/Logger#2]
Hi, I am new to wordpress, I am trying to activate this theme, but it does not work.
wordpress: 6.0.3
php: 8.0
![image](https://user-images.githubusercontent.com/29937602/197387553-ab5ae525-bd0c-4af4-bd03-74ce6d7cea87.png)
![image](https://user-images.githubusercontent.com/29937602/197387632-4ea69ffc-ea41-4b50-802d-b9cc0072b942.png)

**Comment by hzxie** [comment]
Please update the `CDN Base URL` in the `Theme Options`.
In your case, just change it to `http://localhost/wordpress/`.

![Theme-Options](https://user-images.githubusercontent.com/1730504/197435110-b286acbc-539a-44f6-95bf-3405434744c4.jpg)

**Comment by Linon419** [comment]
Thanks, that slove my question, but I still get warnings
![image](https://user-images.githubusercontent.com/29937602/197528062-2336d603-6450-4502-9595-6c7a37684190.png)

**Comment by Linon419** [comment]
Don't mind, I changed the PHP version to 7.4, warnings are gone

**Comment by hzxie** [comment]
@Linon419 
I'll check and fix it in the next few days.
